# Generated by Django 3.2.3 on 2021-09-26 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_auto_20210926_1149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='algorithm',
        ),
        migrations.DeleteModel(
            name='development',
        ),
        migrations.DeleteModel(
            name='language',
        ),
    ]
