# Generated by Django 3.2.3 on 2021-09-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_auto_20210925_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='phone',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='development',
            name='phone',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='language',
            name='phone',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='placement',
            name='phone',
            field=models.CharField(max_length=200),
        ),
    ]
